### ISSUE TITLE
Use `Option.conflicts` of Commander for options / argument that contradict

### ISSUE THREAD

**Issue by lcswillems** [arda-org/xSuite#197]
https://github.com/tj/commander.js?tab=readme-ov-file#more-configuration

In particular, I've in mind the option `--dir` for `build` and `new`.

**Comment by nvergez** [comment]
https://github.com/tj/commander.js/issues/2194

It seems impossible for now to handle conflict between an argument and an option with the `.conflicts()` method

**Comment by lcswillems** [comment]
Indeed, doesn't seem possible
