### ISSUE TITLE
Add a method to easily add Kvs to an existing account

### ISSUE THREAD

**Issue by nvergez** [arda-org/xSuite#200]
To be able to add Kvs to an existing account, we need to do something like this:
```ts
await contract.setAccount({
  ...(await contract.getAccountWithoutKvs()),
  kvs: [
    await contract.getAccountKvs(),
    e.kvs
      .Mapper("points_by_user_by_pool", e.Usize(1), e.U8(0))
      .Value(e.U(10)),
    e.kvs
      .Mapper("points_by_user_by_pool", e.Usize(1), e.U8(1))
      .Value(e.U(100)),
  ],
});
```
which is not very readable nor intuitive.

Or create this kind of helper function:
```ts
export const giveTokensTo = async (wallet: FSWallet, tokens: Esdt[]) => {
  await wallet.setAccount({
    ...(await wallet.getAccountWithoutKvs()),
    kvs: [await wallet.getAccountKvs(), e.kvs.Esdts(tokens)],
  });
};
```

We could add an `appendKvs` method to the `Proxy` and `World`classes:
```ts
appendKvs(address: AddressLike, kvs: EncodableKvs, options?: { overwrite?: boolean }): Promise<void>;
```
And to the `Contract` and `Wallet` classes:
```ts
appendKvs(kvs: EncodableKvs, options?: { overwrite?: boolean }): Promise<void>;
```

We can discuss about the `options` parameter. But I think it's important to let people choose if they want to overwrite the existing Kvs or not.
I think the default behavior should be to overwrite the existing Kvs.

We can also discuss about the naming: `appendKvs`, `appendAccountKvs`, `appendAccount`, ...

Example usage:
```ts
await contract.appendKvs([
  e.kvs
    .Mapper("points_by_user_by_pool", e.Usize(1), e.U8(0))
    .Value(e.U(10)),
  e.kvs
    .Mapper("points_by_user_by_pool", e.Usize(1), e.U8(1))
    .Value(e.U(100)),
]);

await contract.appendKvs({
  mappers: [
    {
      key: ["points_by_user_by_pool", e.Usize(1), e.U8(0)],
      value: e.U(10),
    },
    {
      key: ["points_by_user_by_pool", e.Usize(1), e.U8(1)],
      value: e.U(100),
    },
  ],
});

await wallet.appendKvs({
  esdts: [
    {
      id: "TOKEN-123456",
      amount: 10n ** 18n,
    },
  ],
});
```

**Comment by lcswillems** [comment]
What about `addKvs`? Also, do you have concrete use cases where you need to add kvs?

**Comment by nvergez** [comment]
Yes `addKvs` why not!

For example I used a lot the helper `giveTokensTo` at the start of specific tests where the wallet is already created during a `beforeEach`

**Comment by lcswillems** [comment]
Why not directly adding the tokens?

In order to confirm the use case, could you provide a sample code of your use case? Give a configuration where having such helper would have helped.

**Comment by nvergez** [comment]
A use case:

I have a Minter smart contract that allows users to mint NFTs.
I have a staking smart contract that allows user to stake the NFTs and get rewards.
I have a pool rewards smart contract that owns all the rewards.
A user can mint an NFT using his staking rewards  (without even claiming them).

I want to test only my minter smart contract, so I need to "mock" the staking contract and pool rewards to be able to test the mint logic:

```ts
test("Mint 1 NFT with only rewards", async () => {
  const rewardsAmount = 1_000_000n;

  await stakingContract.setAccount({
    ...(await stakingContract.getAccountWithoutKvs()),
    kvs: [
      await stakingContract.getAccountKvs(),
      e.kvs.Mapper("rewards_by_user", e.Usize(1)).Value(e.U(rewardsAmount)),
    ],
  });
  await poolContract.setAccount({
    ...(await poolContract.getAccountWithoutKvs()),
    kvs: [
      await poolContract.getAccountKvs(),
      e.kvs.Esdts([
        {
          id: tokenId,
          amount: rewardsAmount,
        },
      ]),
    ],
  });

  // Mint

  // Assert everything needed
});
```

I could just add those Kvs at the initialization of the contract, but it won't let me easily strictly assert my kvs in each test.

**Comment by nvergez** [comment]
Design chosen:

We add the following methods to `Contract` and `Wallet` classes, and the equivalent to `World` and `Proxy` classes:

```ts
addKvs(kvs: EncodableKvs);
addEsdts(esdts: Array<EncodableEsdt>);
addMappers(mappers: Array<EncodableMapper>);
```
